services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zync
      POSTGRES_PASSWORD: zync
      POSTGRES_DB: zync
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
