/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List activities */
        get: operations["listActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get activity by ID */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated activity stats */
        get: operations["getActivityStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/stats/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get daily activity stats for charts */
        get: operations["getDailyStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get activity stream data */
        get: operations["getActivityStreams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/strava/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Strava OAuth URL */
        post: operations["getStravaAuthUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current user */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ActivityType: "Run" | "TrailRun" | "VirtualRun" | "Ride" | "MountainBikeRide" | "GravelRide" | "EBikeRide" | "VirtualRide" | "Swim" | "Walk" | "Hike" | "AlpineSki" | "BackcountrySki" | "NordicSki" | "Workout" | "WeightTraining" | "Yoga" | "Other";
        Activity: {
            /** @description Unique activity identifier */
            id: number;
            /** @description Activity name */
            name: string;
            type: components["schemas"]["ActivityType"];
            /** @description Distance in meters */
            distanceMeters: number;
            /** @description Moving time in seconds */
            movingTimeSeconds: number;
            /** @description Total elapsed time in seconds */
            elapsedTimeSeconds: number;
            /** @description Elevation gain in meters */
            elevationGainMeters: number;
            /**
             * Format: date-time
             * @description Activity start time (UTC)
             */
            startDate: string;
            /**
             * Format: date-time
             * @description Activity start time (local timezone)
             */
            startDateLocal: string;
            /** @description Average speed in meters per second */
            averageSpeed: number;
            /** @description Maximum speed in meters per second */
            maxSpeed: number;
            /** @description Average heart rate in BPM */
            averageHeartRate?: number | null;
            /** @description Maximum heart rate in BPM */
            maxHeartRate?: number | null;
            /** @description Number of kudos */
            kudosCount?: number;
            /** @description Number of comments */
            commentCount?: number;
        };
        DetailedActivity: components["schemas"]["Activity"] & {
            description?: string | null;
            calories?: number | null;
            averageCadence?: number | null;
            averageWatts?: number | null;
            maxWatts?: number | null;
            weightedAverageWatts?: number | null;
            sufferScore?: number | null;
            /** @description Start coordinates as [latitude, longitude] */
            startLatLng?: number[] | null;
            /** @description End coordinates as [latitude, longitude] */
            endLatLng?: number[] | null;
            map?: {
                polyline?: string | null;
                summaryPolyline?: string | null;
            } | null;
            laps?: components["schemas"]["Lap"][] | null;
            splitsMetric?: components["schemas"]["Split"][] | null;
        };
        Lap: {
            lapIndex: number;
            name: string;
            distanceMeters: number;
            elapsedTimeSeconds: number;
            movingTimeSeconds: number;
            /** Format: date-time */
            startDate: string;
            totalElevationGain?: number | null;
            averageSpeed?: number | null;
            maxSpeed?: number | null;
            averageHeartRate?: number | null;
            maxHeartRate?: number | null;
        };
        Split: {
            split: number;
            distanceMeters: number;
            elapsedTimeSeconds: number;
            movingTimeSeconds: number;
            elevationDifference?: number | null;
            averageSpeed?: number | null;
            paceZone?: number | null;
        };
        User: {
            /** @description Unique user identifier */
            id: number;
            firstName: string;
            lastName: string;
            /** @description URL to profile image */
            profileUrl: string;
            city?: string | null;
            state?: string | null;
            country?: string | null;
        };
        GetActivitiesResponse: {
            activities: components["schemas"]["Activity"][];
            page: number;
            perPage: number;
            hasMore: boolean;
            /** @description Total number of activities (only available when no date filters applied) */
            totalCount?: number;
            cached?: boolean;
        };
        GetActivityResponse: {
            activity: components["schemas"]["DetailedActivity"];
            cached?: boolean;
        };
        GetMeResponse: {
            user: components["schemas"]["User"];
            /** @description Unix timestamp when token expires */
            tokenExpiresAt?: number;
        };
        GetAuthUrlRequest: {
            /** Format: uri */
            redirectUri: string;
        };
        GetAuthUrlResponse: {
            /** Format: uri */
            url: string;
            state: string;
        };
        LogoutResponse: {
            message: string;
        };
        /** @enum {string} */
        StatsPeriod: "week" | "last_week" | "month" | "year" | "last_year" | "all";
        GetActivityStatsResponse: {
            period: components["schemas"]["StatsPeriod"];
            /** @description Total moving time in seconds */
            totalMovingTimeSeconds: number;
            /** @description Total cycling distance in meters */
            cyclingDistanceMeters: number;
            /** @description Total running distance in meters */
            runningDistanceMeters: number;
            /** @description Total calories burned */
            totalCalories: number;
            /** @description Number of activities in the period */
            activityCount: number;
            /** @description Current consecutive days with activities */
            currentStreak: number;
            /** @description All-time longest consecutive days with activities */
            longestStreak: number;
            /** @description Start date of the longest streak (YYYY-MM-DD) */
            longestStreakStart?: string | null;
            /** @description End date of the longest streak (YYYY-MM-DD) */
            longestStreakEnd?: string | null;
        };
        DailyStatsItem: {
            /** @description Date in YYYY-MM-DD format */
            date: string;
            /** @description Total activity hours for the day */
            hours: number;
            /** @description Total distance in kilometers for the day */
            distanceKm: number;
            /** @description Total calories burned for the day */
            calories: number;
            /** @description Number of activities for the day */
            activityCount: number;
        };
        GetDailyStatsResponse: {
            period: components["schemas"]["StatsPeriod"];
            data: components["schemas"]["DailyStatsItem"][];
        };
        GetActivityStreamsResponse: {
            /** @description Time in seconds since activity start */
            time: number[];
            /** @description Heart rate in BPM */
            heartrate?: number[] | null;
            /** @description Velocity in meters per second */
            velocity?: number[] | null;
            /** @description Altitude in meters */
            altitude?: number[] | null;
            /** @description Power output in watts */
            power?: number[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listActivities: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Unix timestamp - only activities before this time */
                before?: number;
                /** @description Unix timestamp - only activities after this time */
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetActivitiesResponse"];
                };
            };
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetActivityResponse"];
                };
            };
        };
    };
    getActivityStats: {
        parameters: {
            query?: {
                /** @description Time period for stats */
                period?: "week" | "last_week" | "month" | "year" | "last_year" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetActivityStatsResponse"];
                };
            };
        };
    };
    getDailyStats: {
        parameters: {
            query?: {
                /** @description Time period for stats */
                period?: "week" | "last_week" | "month" | "year" | "last_year" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDailyStatsResponse"];
                };
            };
        };
    };
    getActivityStreams: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetActivityStreamsResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMeResponse"];
                };
            };
        };
    };
    getStravaAuthUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetAuthUrlRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAuthUrlResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
}
